image: node:18

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run docs:build 
  artifacts:
    paths:
      - src/.vuepress/dist 
  only:
    - main 


pages:
  stage: deploy
  script:
    - cp -r src/.vuepress/dist public 
  artifacts:
    paths:
      - public 
  only:
    - main 