image: node:22

pages:
  stage: build
  cache:
    paths:
      - node_modules/
  before_script:
    - apk add --no-cache git
    - npm install -g pnpm
  script:
    - pnpm install
    - pnpm run docs:build
  artifacts:
    expire_in: 1h30min
    paths:
      - src/.vuepress/dist
  only:
    - main 