image: node:20.17.0

pages:
  stage: build
  cache:
    paths:
      - node_modules/
  before_script:
    - npm install -g pnpm
  script:
    - pnpm install
    - pnpm run docs:build
    - mv src/.vuepress/dist public
  artifacts:
    expire_in: 1h30min
    paths:
      - public
  only:
    - main
