image: node:20.17.0

pages:
  stage: build
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - node_modules/
  before_script:
    - npm install -g pnpm
    - pnpm config set store-dir node_modules/
  script:
    - pnpm install --frozen-lockfile
    - pnpm docs:build --dest public
  artifacts:
    expire_in: 1h30min
    paths:
      - public
  only:
    - main
