<<<<<<< HEAD
image: node:20
=======
image: node:22
>>>>>>> b6b07155f7052afc08f4d7e63933b1d0ea53ab09

pages:
  stage: build
  cache:
    paths:
      - node_modules/
  before_script:
<<<<<<< HEAD
    - apk add --no-cache git
=======
>>>>>>> b6b07155f7052afc08f4d7e63933b1d0ea53ab09
    - npm install -g pnpm
  script:
    - pnpm install
    - pnpm run docs:build
  artifacts:
    expire_in: 1h30min
    paths:
      - src/.vuepress/dist
  only:
    - main 